// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUTUM4pO74Q-8VjEi7QKPvns5zscNRdeM',
    appId: '1:325336282488:web:d44fc2ca8bed265e96c48d',
    messagingSenderId: '325336282488',
    projectId: 'polen-academy',
    authDomain: 'polen-academy.firebaseapp.com',
    storageBucket: 'polen-academy.firebasestorage.app',
    measurementId: 'G-NSYZS7C49D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeF7DP0pqImzLA9ZmfdIxvsgr1ZtdmRS0',
    appId: '1:325336282488:android:c912f9f6b1d1f8f896c48d',
    messagingSenderId: '325336282488',
    projectId: 'polen-academy',
    storageBucket: 'polen-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJhjPDZHhS-z8NHd78tiMhxsJLHhy5Lc',
    appId: '1:325336282488:ios:6930aedd80a018fd96c48d',
    messagingSenderId: '325336282488',
    projectId: 'polen-academy',
    storageBucket: 'polen-academy.firebasestorage.app',
    iosClientId: '325336282488-5r7jqhul6tls098fghi64goledav0lea.apps.googleusercontent.com',
    iosBundleId: 'com.example.polenAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJhjPDZHhS-z8NHd78tiMhxsJLHhy5Lc',
    appId: '1:325336282488:ios:6930aedd80a018fd96c48d',
    messagingSenderId: '325336282488',
    projectId: 'polen-academy',
    storageBucket: 'polen-academy.firebasestorage.app',
    iosClientId: '325336282488-5r7jqhul6tls098fghi64goledav0lea.apps.googleusercontent.com',
    iosBundleId: 'com.example.polenAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUTUM4pO74Q-8VjEi7QKPvns5zscNRdeM',
    appId: '1:325336282488:web:01b6b0a5872a3d6796c48d',
    messagingSenderId: '325336282488',
    projectId: 'polen-academy',
    authDomain: 'polen-academy.firebaseapp.com',
    storageBucket: 'polen-academy.firebasestorage.app',
    measurementId: 'G-SHF6Y5X4VB',
  );
}