// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWUiik2cDiher1jW8KAZ2Rl0-88znUpro',
    appId: '1:639274232378:web:43b783446f0274044b2303',
    messagingSenderId: '639274232378',
    projectId: 'polen-akademi',
    authDomain: 'polen-akademi.firebaseapp.com',
    storageBucket: 'polen-akademi.firebasestorage.app',
    measurementId: 'G-9P36TYPSFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo1aG9v_MSRIxc8aPsYqVcvQmpWLaADpI',
    appId: '1:639274232378:android:127eb5af48fea4c74b2303',
    messagingSenderId: '639274232378',
    projectId: 'polen-akademi',
    storageBucket: 'polen-akademi.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDROGuCk-5T9Xs45EzjhAaB-b6OEZuZmI',
    appId: '1:639274232378:ios:e31177b35f71f3a24b2303',
    messagingSenderId: '639274232378',
    projectId: 'polen-akademi',
    storageBucket: 'polen-akademi.firebasestorage.app',
    iosBundleId: 'com.polenolcer.polenacademy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDROGuCk-5T9Xs45EzjhAaB-b6OEZuZmI',
    appId: '1:639274232378:ios:e31177b35f71f3a24b2303',
    messagingSenderId: '639274232378',
    projectId: 'polen-akademi',
    storageBucket: 'polen-akademi.firebasestorage.app',
    iosBundleId: 'com.polenolcer.polenacademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWUiik2cDiher1jW8KAZ2Rl0-88znUpro',
    appId: '1:639274232378:web:7966db45180290a04b2303',
    messagingSenderId: '639274232378',
    projectId: 'polen-akademi',
    authDomain: 'polen-akademi.firebaseapp.com',
    storageBucket: 'polen-akademi.firebasestorage.app',
    measurementId: 'G-KSCFXQV5EM',
  );
}
